---
language: node_js
node_js:
  - node
  - lts/*
cache:
  yarn: true
  directories:
    - node_modules
    - .jest
    - .yarn
script:
  - yarn global add yarn@latest
  - yarn install --frozen-lockfile

jobs:
  include:
    - stage: test
      node_js: lts/*
      script:
        - yarn lint --format junit --output-file ./reports/eslint/eslint.xml
    - stage: deploy # Deploy to Expo account
      # Develop branch = beta
      if: branch = develop
      node_js: lts/*
      before_script:
        - yarn add expo-cli
      script:
        - yarn install --frozen-lockfile # Clear the project and reinstall using cache for fresh start
        - yarn expo login --username $EXPO_USERNAME --password $EXPO_PASSWORD
        - travis_wait 30 yarn expo publish --quiet --release-channel stores --non-interactive # Push to the associated Expo account
    - stage: build # Build
      # Main branch = Release
      if: branch = main
      node_js: lts/*
      before_script:
        - yarn add eas-cli
      script:
        - yarn install --frozen-lockfile # Clear the project and reinstall using cache for fresh start
        - travis_wait 30 eas build --platform=all --auto-submit --clear-cache --non-interactive --wait
