---
language: node_js
node_js:
  - node
  - lts/*
cache:
  yarn: true
  directories:
    - node_modules
    - .jest
    - .yarn
script:
  - yarn global add yarn@latest
  - yarn install --frozen-lockfile # Clear the project and reinstall using cache for fresh start

jobs:
  include:
    - stage: test
      node_js: lts/*
      script:
        - yarn lint --format junit --output-file ./reports/eslint/eslint.xml
    - stage: deploy # Deploy to Expo account
      # Develop branch = beta
      if: branch = develop
      node_js: lts/*
      before_script:
        - yarn add expo-cli
      script:
        - yarn install --frozen-lockfile # Clear the project and reinstall using cache for fresh start
        - yarn expo login --username $EXPO_USERNAME --password $EXPO_PASSWORD
        - travis_wait 30 yarn expo publish --quiet --non-interactive # Push to the associated Expo account
    - stage: build_release_ios # Build
      # Main branch = Release
      if: branch = main
      node_js: lts/*
      before_script:
        - yarn add expo-cli
      script:
        - yarn install --frozen-lockfile # Clear the project and reinstall using cache for fresh start
        - yarn expo login --username $EXPO_USERNAME --password $EXPO_PASSWORD
        - travis_wait 30 yarn expo bi --skip-workflow-check --no-publish --type archive --release-channel stores --skip-credentials-check > buildout.txt
        - bundle check || bundle install
        - mkdir build
        - curl --output ./build/Counter.ipa --url $(grep -o https://expo.io/artifacts/.* buildout.txt) -L
        - bundle exec fastlane release
    - stage: build_release_android # Build Android
      # Main branch = Release
      if: branch = main
      node_js: lts/*
      before_script:
        - yarn add expo-cli
      script:
        - yarn install --frozen-lockfile # Clear the project and reinstall using cache for fresh start
        - yarn expo login --username $EXPO_USERNAME --password $EXPO_PASSWORD
        - travis_wait 30 yarn expo ba --skip-workflow-check --no-publish --type apk --release-channel stores > buildout.txt
        - mkdir build
        - curl --output ./build/Counter.ipa --url $(grep -o https://expo.io/artifacts/.* buildout.txt) -L
