lane :release do
  api_key = app_store_connect_api_key(
    duration: 1200, # optional (maximum 1200)
    in_house: false, # optional but may be required if using match/sigh
    is_key_content_base64: false
  )

  # Changelog
  readme_data = YAML.safe_load(File.read('../CHANGELOG.yml'))
  change_log_list = readme_data['upcoming']['user_facing'] || []

  deliver(
    api_key: api_key,
    ipa: "./build/Counter.ipa".freeze,
    force: true,
    submit_for_review: true,
    automatic_release: true,
    copyright: "#{Time.now.year} Hundter Biede".freeze,
    release_notes: {
        'default' => (change_log_list.length() > 0 ? ("- #{change_log_list.join("\n - ")}") : '').freeze,
    },
    run_precheck_before_submit: false,
    precheck_include_in_app_purchases: false,
    submission_information: {
      add_id_info_serves_ads: false,
      add_id_info_tracks_action: false,
      add_id_info_tracks_install: false,
      add_id_info_uses_idfa: false,
      content_rights_contains_third_party_content: false,
      export_compliance_platform: 'ios',
      export_compliance_encryption_updated: false,
      export_compliance_uses_encryption: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false
    }
  )
end
