lane :release do
  api_key = app_store_connect_api_key(
    key_filepath: "./build/Key.p8",
    duration: 1200, # optional (maximum 1200)
    in_house: false, # optional but may be required if using match/sigh
    is_key_content_base64: false
  )

  deliver(
    api_key: api_key,
    ipa: "./build/Counter.ipa",
    force: true,
    run_precheck_before_submit: false,
    precheck_include_in_app_purchases: false
  )
end